### ISSUE TITLE
OS Permission Denied Error during enable overcommit in sysctl step

### ISSUE THREAD

**Issue by ryanisnan** [DavidWittman/ansible-redis#64]
Thanks for creating this playbook! I'm having a small problem during installation, and I'm not 100% sure if it's a problem with the package or my vagrant box, or with something I'm doing.

Here's the output I'm getting when I attempt to provision:

    ...
    
    TASK: [DavidWittman.redis | install dependencies] ***************************** 
    ok: [default] => (item=gcc,make,libc6-dev)

    TASK: [DavidWittman.redis | install dependencies] ***************************** 
    skipping: [default]

    TASK: [DavidWittman.redis | enable overcommit in sysctl] ********************** 
    failed: [default] => {"failed": true, "parsed": false}
    Traceback (most recent call last):
      File "/home/vagrant/.ansible/tmp/ansible-tmp-1429466343.23-73074173030441/sysctl", line 1936, in <module>
        main()
      File "/home/vagrant/.ansible/tmp/ansible-tmp-1429466343.23-73074173030441/sysctl", line 335, in main
        result = SysctlModule(module)    
      File "/home/vagrant/.ansible/tmp/ansible-tmp-1429466343.23-73074173030441/sysctl", line 118, in __init__
        self.process()
      File "/home/vagrant/.ansible/tmp/ansible-tmp-1429466343.23-73074173030441/sysctl", line 164, in process
        self.write_sysctl()
      File "/home/vagrant/.ansible/tmp/ansible-tmp-1429466343.23-73074173030441/sysctl", line 302, in write_sysctl
        fd, tmp_path = tempfile.mkstemp('.conf', '.ansible_m_sysctl_', os.path.dirname(self.sysctl_file))
      File "/usr/lib/python2.7/tempfile.py", line 300, in mkstemp
        return _mkstemp_inner(dir, prefix, suffix, flags)
      File "/usr/lib/python2.7/tempfile.py", line 235, in _mkstemp_inner
        fd = _os.open(file, flags, 0600)
    OSError: [Errno 13] Permission denied: '/etc/.ansible_m_sysctl_lh1_3d.conf'

    FATAL: all hosts have already failed -- aborting

    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/Users/ryanisnan/vagrant.retry

    default                    : ok=7    changed=5    unreachable=0    failed=1   

    Ansible failed to complete successfully. Any error output should be
    visible above. Please fix these errors and try again.

**Comment by ryanisnan** [comment]
I managed to solve this issue by making ansible provision as root. For future reference, here's the provisioning statement.

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/vagrant.yml"
      ansible.sudo = true  # Added this line
    end

**Comment by DavidWittman** [comment]
Hey @ryanisnan, thanks for the update. I'll make some changes to the documentation to make this more clear.
